# MAIN file to install the Cpanel
# script execution for desa --> ansible-playbook -i inventory install_cpanel.yml -e devpro=dev
- name: Start the cpanel installation with Ansible
  hosts: cpanelserver
  remote_user: aminaya
  become: true
  gather_facts: true

#we ask what environment yo want to use for the installation
  vars_prompt:
    - name: devpro
      prompt: Please enter the environment - pro or dev
      private: no
      tags: [soft_base,STEP_02]

#we evaluate that the distribution is ubuntu
  tasks:
    - fail: msg="The Distro is = {{ ansible_distribution }}, can only be installed on Ubuntu"
      when: ansible_distribution != "Ubuntu"


  roles:
    #we call the roll to install base software
    # STEP_01.00 TO STEP_02.20
    # - { role: softwarebase}
    # - { role: webserver}
    - softwarebase
    - webserver
