- name: STEP_01 - Software installation.
  include: softwarebase.yml
#We include the softwaredesa file for a development environment
- name: we include the file to install software for development.
  include: softwaredesa.yml
  when: devpro == "dev"
  #when: "'desa' in ambiente"
