---
# tasks file for webserver

- name: We print the steps to execute, Steps to work STEP_03.00 TO STEP_03.4
  pause: seconds=2
  tags: [webserver,STEP_03]

- name: STEP_03.01 -> Install Apache2
  apt: name=apache2 state=latest
  tags: [webserver,STEP_03]

- name: STEP_03.02 -> Install Moduler; Json,curl,ssh,cgi,php7.
  apt:
    name:
      - php7.4-curl
      - php7.4-json
      - php7.4-cgi
      - php7.4
      - libapache2-mod-php7.4
      - php-mbstring
      - php-ssh2
    # name: "{{ lista_paquetes }}"
    state: present
  tags: [webserver,STEP_03]

- name: STEP_03.03 -> Install more Moduler; mysql,pgsql,phpmailer,soap.
  apt:
    name:
      - php7.4-pgsql
      - php7.4-mysql
      - libphp-phpmailer
      - php-soap
    state: present
  tags: [webserver,STEP_03]

- name: STEP_03.04 -> Install more php7.4-dev, php-pear,build-essential,libaio1.
  apt:
    name:
      - php7.4-dev
      - php-pear
      - build-essential
      - libaio1
    state: present
  tags: [webserver,STEP_03]

- name: STEP_03.05 -> Change the default directory to the controlpanel
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="/var/www/html" line="\tDocumentRoot {{controlpanel_dir}}" state=present
  notify:
    - Restart_Apache
  tags: [webserver,STEP_03]

# - name: STEP_03.06 -> Change the certified path
#   lineinfile: dest=/etc/apache2/sites-available/default-ssl.conf regexp="^SSLCertificateFile" line="\t\tSSLCertificateFile\t{{cert_dir}}/cpanel.crt" state=present
#   notify:
#     - Restart_Apache
#   tags: [webserver,STEP_03,STEP_03]

- name: STEP_03.06 -> Change the certified pathand key
  copy:
   src: "default-ssl.conf"
   dest: "/etc/apache2/sites-available/"
  notify:
    - Restart_Apache
  tags: [webserver,STEP_03]

- name: STEP_03.07 -> execute a command a2enmod
  command: 'a2enmod ssl'
  tags: [webserver,STEP_03]

- name: STEP_03.08 -> execute a command a2ensite
  command: 'a2ensite default-ssl.conf'
  notify:
    - Restart_Apache
  tags: [webserver,STEP_03]
