
#we create the application group
- name: STEP_04.01 -> Creating group cpanel
  group:
    name: cpanel
    state: present
  tags: [webserver,STEP_04]

#we create the application user
- name: STEP_04.02 -> Add the user cpanel
  user:
    name: cpanel
    shell: /bin/bash
    groups: cpanel
    home: /var/www/controlpanel
    append: yes
  tags: [webserver,STEP_04]

- name: STEP_04.03 -> we create the controlpanel directory and assign permissions
  file:
    path: /var/www/controlpanel
    state: directory
    owner: cpanel
    group: cpanel
    mode: 0775
    recurse: yes
