---
- name: We print the steps to execute, Steps to work STEP_04.00 TO STEP_03.5
  pause: seconds=2
  tags: [webserver,STEP_04]
#we create the application group
- name: STEP_04.01 -> Creating group cpanel
  group:
    name: "{{cpanel_user}}"
    state: present
  tags: [webserver,STEP_04]

#we create the application user
- name: STEP_04.02 -> Add the user cpanel
  user:
    name: "{{cpanel_user}}"
    password: "{{password_cpanel | password_hash('sha512') }}"
    shell: /bin/bash
    groups: "{{cpanel_gourp}}"
    home: "{{controlpanel_dir}}"
    append: yes
  tags: [webserver,STEP_04]

- name: STEP_04.03 -> we create the controlpanel directory and assign permissions
  file:
    path: "{{controlpanel_dir}}"
    state: directory
    owner: "{{cpanel_user}}"
    group: "{{cpanel_gourp}}"
    mode: 0775
    recurse: yes
  tags: [webserver,STEP_04]

- name: STEP_04.04 -> copy and unzip the file controlpanel.tar into /var/www
  unarchive:
    src: controlpanel.tar
    dest: "{{www_dir}}"
  tags: [webserver,STEP_04]

- name: STEP_04.05 -> we copy the .profile where the environment variables are located
  template:
    dest: "{{controlpanel_dir}}"
    src: ".profile"
  tags: [webserver,STEP_04]

- name: STEP_04.06 -> Recursively change ownership of a directory
  ansible.builtin.file:
    path: "{{controlpanel_dir}}"
    state: directory
    recurse: yes
    owner: cpanel
    group: cpanel
#name: STEP_04.05 -> we copy the .profile where the environment variables are located
