#we create the application group
- name: STEP_04.01 -> Creating group cpanel
  group:
    name: "{{cpanel_user}}"
    state: present
  tags: [webserver,STEP_04]

#we create the application user
- name: STEP_04.02 -> Add the user cpanel
  user:
    name: "{{cpanel_user}}"
    password: "{{password_cpanel}}"
    shell: /bin/bash
    groups: "{{cpanel_gourp}}"
    home: "{{controlpanel_dir}}"
    append: yes
  tags: [webserver,STEP_04]

- name: STEP_04.03 -> we create the controlpanel directory and assign permissions
  file:
    path: "{{controlpanel_dir}}"
    state: directory
    owner: "{{cpanel_user}}"
    group: "{{cpanel_gourp}}"
    mode: 0775
    recurse: yes
  tags: [webserver,STEP_04]
